name: bestfriend
description: My goto architecture
version: 1.0.0
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_screenutil: ^5.0.0+2
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  provider: ^6.1.1
  shared_preferences: ^2.0.6
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: null

flutter: null
